### ISSUE TITLE
libyal windows build failure

### ISSUE THREAD

**Issue by dfirfpi** [libyal/libyal#15]
libyal-build is able to build one project at time using VisualStudio version different from 2008 and x64 environment.

The issue is due to lines 1348-to-1355, when preparing for MSI file creation: if self.version is not '2008', the os.environ dict is enriched with the 'VS90COMNTOOLS' key. When preparing for the next project build, the LibyalMsiBuildHelper initilization will detect the presence of 'VS90COMNTOOLS' in os.environ (lines 1134-1125), setting the self.version variable to '2008', which is wrong.

I patched my local libyal-build adding the following lines after current line 1371:

      if self.version != '2008':
        del os.environ['VS90COMNTOOLS']

**Comment by joachimmetz** [comment]
Thanks for reporting this, I'll likely deprecate libyal-sync.py infavor of [l2tdevtools build.py](https://github.com/log2timeline/l2tdevtools/blob/master/tools/build.py)

**Comment by joachimmetz** [comment]
https://github.com/libyal/libyal/commit/a0453f13169c7f9cc074308a01f05979028fec67
