### ISSUE TITLE
Change CI tests to build Python wheels for different platforms and Python versions

### ISSUE THREAD

**Issue by joachimmetz** [libyal/libyal#94]
* [x] Change CI tests to use tox to build Python wheels for different platforms and Python versions
* [x] Upload wheels to pypi on release

**Comment by pombredanne** [comment]
repasting here for reference from https://github.com/libyal/libfwsi/issues/19#issue-1320116185

> FWIW, I use this as an example for a project that I co-maintain https://github.com/WojciechMula/pyahocorasick/blob/master/.github/workflows/test-and-build.yml (Stolen with credits from Google's brotli repo)


@joachimmetz tell me if you want help!

**Comment by joachimmetz** [comment]
@pombredanne thx for the offer though I prefer to be able to troubleshoot the wheel builds locally (hence the choice for using tox) and use appveyor for automatic deployment (seeing previous issues with GitHub security tokens)

**Comment by joachimmetz** [comment]
Changes for building and distributing Windows wheels in https://github.com/libyal/libyal/commit/b40cb82e82b7441a973195b26955c0e8c778d90d and https://github.com/libyal/libfwsi/commit/200c2bde0d3505d53273b9bd952e9c46886ad4fd

**Comment by joachimmetz** [comment]
Closing issue. Work for an ubuntu22.04 built wheel for Linux in the pipeline. However most Linux distros have their own packaging ecosystem which is recommended over PyPI (especially when not using virtualenv).

**Comment by joachimmetz** [comment]
```
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Binary wheel 'libfwnt_python-20240126-cp310-cp310-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'.
Command exited with code 1
Build failed
```
