### ISSUE TITLE
How do I use libyal in combination with vcpkg ports?

### ISSUE THREAD

**Issue by eyalgolan1337** [libyal/libyal#97]
Hey, I'm attempting to port a large number of libyal libraries to the package manager vcpkg.
Libraries ports in vcpkg cannot contain bundled libraries not ported by vcpkg as those can create collisions.
This means for every libyal library I want to port I need to port all of it's dependencies (libcerror, libclocale, etc...) this is fine and works perfectly fine in Linux where you can supply the `--with-libcerror=yes` flag, but there is no such alternative for Windows.

I implemented a vcpkg wrapper for the msvcpp-convert utility, and use it to build on Windows - mirroring the upstream way to build for Windows.
You can take a look at my [libcdatetime VCPKG port PR](https://github.com/microsoft/vcpkg/pull/38491) to see an example.
Currently as it stands, the library fails building on Windows because the bundled libcerror that comes with libcdatetime conflicts with the existing libcerror port.
Would love your help in getting this working, porting libyal to vcpkg would make it more accessible and allow porting other libraries that use libyal.

Thanks!

**Comment by joachimmetz** [comment]
> Libraries ports in vcpkg cannot contain bundled libraries not ported by vcpkg as those can create collisions.

Unfortunately this is not how the libraries are intended to be used.

**Comment by joachimmetz** [comment]
> It's supported on linux/mingw though, using the --with- flag, why the inconsistency?

so `--with-` allows to use either a shared library version of the dependency or it will fallback on the local version of dependency. You indicated that "vcpkg cannot contain bundled libraries", so this is not an inconsistency but a limitation of vcpkg that conflicts with intended use case.

**Comment by joachimmetz** [comment]
> This work perfectly in posix build systems, on Windows though there is no such flag.

You are conflating Windows with the msvscpp. MinGW and CygWin also run on Windows

> vcpkg can contain ports of libraries containing bundled libraries as long as you can override the dependency and use your own version of that bundled library - there are many such cases.

Then vcpkg must have some mechanism similar to configure (autotools) to set up the (msvscpp) build files?

**Comment by joachimmetz** [comment]
> vcpkg indeed has a way to configure, it invokes msbuild - in order to use it I first call your msvcpp-convert script.

And what mechanism does vcpkg provide? you likely need to change https://github.com/libyal/vstools so that it can leverage this mechanism

To my knowledge msbuild has limited support for build configurations compared to autotools. E.g. how do you test if you have the right version of the library as dependency?

**Comment by joachimmetz** [comment]
> The mechanism is simply calling msbuild, passing options etc... 

autotools does more, it checks the version of the dependency and sees if the necessary functions are available. It sets up the build configuration. The functionality of msbuild sounds comparable to make, there is more to the build process. msvscpp supports advanced configuration, not sure how portable this is for msbuild. You might need to make changes how it generates the visual studio project files.

**Comment by joachimmetz** [comment]
No additional replies from original reporter, assuming question was answered. Closing
